# Generated by Django 5.0.11 on 2025-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('emp_no', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updated_by', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
