# Generated by Django 5.0.11 on 2025-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripBranchModel',
            fields=[
                ('branch_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fin_mf_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripDetailsModel',
            fields=[
                ('trip_ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('branch_id', models.BigIntegerField()),
                ('full_address', models.TextField()),
                ('trans_name', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('branch_charges', models.DecimalField(decimal_places=2, max_digits=18)),
                ('document_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripDriverModel',
            fields=[
                ('entity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fin_mf_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripTicketModel',
            fields=[
                ('trip_ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.BigIntegerField()),
                ('plate_no', models.CharField(max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('asst_entity_id', models.BigIntegerField()),
                ('trip_ticket_date', models.DateTimeField()),
                ('trip_ticket_delivery_type_id', models.BigIntegerField()),
                ('dispatched_by', models.BigIntegerField()),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
    ]
