# Generated by Django 5.0.11 on 2025-02-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutslipImagesModel',
            fields=[
                ('server_id', models.BigIntegerField()),
                ('trip_ticket_id', models.BigIntegerField()),
                ('upload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_ticket_detail_id', models.BigIntegerField()),
                ('upload_remarks', models.CharField(blank=True, max_length=4000, null=True)),
                ('upload_files', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.BigIntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_fap', models.BooleanField(default=False)),
                ('is_candis', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scm_tr_outslip_to_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripTicketBranchLogsModel',
            fields=[
                ('server_id', models.BigIntegerField()),
                ('trip_ticket_id', models.BigIntegerField()),
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_ticket_detail_id', models.BigIntegerField()),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.BigIntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_fap', models.BooleanField(default=False)),
                ('is_candis', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket_branch_logs',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='outslipimagesmodel',
            constraint=models.UniqueConstraint(fields=('server_id', 'trip_ticket_id'), name='outslip_images_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='tripticketbranchlogsmodel',
            constraint=models.UniqueConstraint(fields=('server_id', 'trip_ticket_id'), name='branch_logs_composite_pk'),
        ),
    ]
