# Generated by Django 5.0.11 on 2025-01-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
